### ISSUE TITLE
On mouseover the label disappears

### ISSUE THREAD

**Issue by palamago** [d3plus/d3plus-shape#61]
### Current Behavior
The shape label disappears.
![sept-06-2017 12-32-28](https://user-images.githubusercontent.com/1203432/30121789-037c844a-9303-11e7-9b72-f355bf664ca5.gif)

You can reproduce the issue on this example: https://d3plus.org/examples/d3plus-hierarchy/selecting-container/

### Steps to Reproduce (for bugs)

1. Load a treemap chart : https://d3plus.org/examples/d3plus-hierarchy/selecting-container/
2. Place the mouse over of any shape.
3. You will see.

### Your Environment

* Browser Name: chrome
* Operating System and Version: OSx El capitán

**Comment by davelandry** [comment]
Working on this now. Kudos to @palamago for actually filling out the full bug report 😍

**Comment by palamago** [comment]
Reopen, because I think this bug is related:
![sept-11-2017 17-24-16](https://user-images.githubusercontent.com/1203432/30295175-14713f90-9716-11e7-8729-d04896c92813.gif)
Happens when you have a chart with timeseries.
After you hover the label always stay on top.
