### ISSUE TITLE
Shapes truncate long names

### ISSUE THREAD

**Issue by cnavarreteliz** [d3plus/d3plus-shape#80]
https://jsfiddle.net/7b5h2oxa/

![image](https://user-images.githubusercontent.com/5233593/41040137-8a27dd68-6969-11e8-82f1-37ce0141c4ac.png)

**Comment by davelandry** [comment]
Fixed in latest `d3plus-text` release, discussion here: https://github.com/d3plus/d3plus-text/issues/76
