### ISSUE TITLE
labels are misaligned when rotating shapes

### ISSUE THREAD

**Issue by davelandry** [d3plus/d3plus-shape#83]
### Expected Behavior
When rotating a shape, the labels should rotate with it.

### Current Behavior
Currently, as a shape rotates away from 0, the vertical alignment of the label becomes misaligned. Here is the code inside of `Shape.js` which sets the label rotation: https://github.com/d3plus/d3plus-shape/blob/master/src/Shape/Shape.js#L435-L439

This might actually be an issue with `d3plus-text`, so maybe test it there if you're hitting a brick wall.

### Steps to Reproduce (for bugs)
https://jsfiddle.net/nfd9bo8q/54/

**Comment by cnavarreteliz** [comment]
I found a brick wall in d3plus-shape, so I'm testing in d3plus-text 😃

**Comment by cnavarreteliz** [comment]
I mean, I disabled `.rotate()` in d3plus/shape: [https://github.com/d3plus/d3plus-shape/blob/master/src/Shape/Shape.js#L467](https://github.com/d3plus/d3plus-shape/blob/master/src/Shape/Shape.js#L467), and the results are:
![image](https://user-images.githubusercontent.com/5233593/44115788-26f816e2-9fe5-11e8-874d-649f181205b1.png)

So, I think that I can discard an issue related directly with `d3plus-shape`.

**Comment by davelandry** [comment]
It's probably related to not only the `rotate` of TextBox but also the `[rotateAnchor](https://github.com/d3plus/d3plus-text#TextBox.rotateAnchor)`. I drew a little diagram to make sure we're on the same page:

![img_1915](https://user-images.githubusercontent.com/1847581/44153172-760a9cba-a075-11e8-9158-09dc379faa22.jpg)

**Comment by cnavarreteliz** [comment]
I was experimenting and I think that the problem is related with `rotateAnchor` and `rotate(angle, cx, cy)` in `d3plus-text`. I hope to have news ASAP. 

![image](https://user-images.githubusercontent.com/5233593/44235326-7a535400-a17f-11e8-809e-70c0db5f0e3b.png)
