### ISSUE TITLE
D3plus Line Plot : lines are not continuous 

### ISSUE THREAD

**Issue by nalhadad** [d3plus/d3plus-shape#94]
Hello,
I am new to your library,, I'm trying to create a line plot which is apears not continuous (there is no 0 values) . I even have some isolated points despite that they belong to a line . did I do something wrong? 

[http://jsfiddle.net/exd0z1oh/2/]

here is my example in case the link does not work:
<script src="http://www.d3plus.org/js/d3.min.js"></script>
<script src="http://www.d3plus.org/js/d3plus.min.js"></script>

<div id="viz"></div><div id="viz1"></div>
<script>
var sample_data=[{"LivraisonPays":"Argentina" , "year":2015 , "Prix":3 },
{"LivraisonPays":"Argentina" , "year":2022 , "Prix":81 },
{"LivraisonPays":"Argentina" , "year":2014 , "Prix":81 },
{"LivraisonPays":"Argentina" , "year":2022 , "Prix":264 },
{"LivraisonPays":"Austria" , "year":2020 , "Prix":2 },
{"LivraisonPays":"Austria" , "year":2016 , "Prix":4 },
{"LivraisonPays":"Austria" , "year":2023 , "Prix":5 },
{"LivraisonPays":"Austria" , "year":2017 , "Prix":6 },
{"LivraisonPays":"Austria" , "year":2021 , "Prix":7 },
{"LivraisonPays":"Austria" , "year":2019 , "Prix":8 },
{"LivraisonPays":"Austria" , "year":2014 , "Prix":8 },
{"LivraisonPays":"Austria" , "year":2021 , "Prix":8 },
{"LivraisonPays":"Austria" , "year":2016 , "Prix":8 },
{"LivraisonPays":"Austria" , "year":2020 , "Prix":8 },
{"LivraisonPays":"Austria" , "year":2020 , "Prix":8 },
{"LivraisonPays":"Austria" , "year":2014 , "Prix":30 },
{"LivraisonPays":"Austria" , "year":2022 , "Prix":30 },
{"LivraisonPays":"Austria" , "year":2020 , "Prix":31 },
{"LivraisonPays":"Austria" , "year":2013 , "Prix":31 },
{"LivraisonPays":"Austria" , "year":2019 , "Prix":31 },
{"LivraisonPays":"France" , "year":2012 , "Prix":2 },
{"LivraisonPays":"France" , "year":2023 , "Prix":3 },
{"LivraisonPays":"France" , "year":2014 , "Prix":3 },
{"LivraisonPays":"France" , "year":2020 , "Prix":4 },
{"LivraisonPays":"France" , "year":2021 , "Prix":5 },
{"LivraisonPays":"France" , "year":2015 , "Prix":5 },
{"LivraisonPays":"France" , "year":2019 , "Prix":6 },
{"LivraisonPays":"France" , "year":2012 , "Prix":6 },
{"LivraisonPays":"France" , "year":2018 , "Prix":6 },
{"LivraisonPays":"France" , "year":2020 , "Prix":6 },
{"LivraisonPays":"France" , "year":2020 , "Prix":6 },
{"LivraisonPays":"France" , "year":2021 , "Prix":6 },
{"LivraisonPays":"France" , "year":2012 , "Prix":6 },
{"LivraisonPays":"France" , "year":2020 , "Prix":6 },
{"LivraisonPays":"France" , "year":2022 , "Prix":6 },
{"LivraisonPays":"France" , "year":2013 , "Prix":6 },
{"LivraisonPays":"France" , "year":2022 , "Prix":6 },
{"LivraisonPays":"France" , "year":2019 , "Prix":7 },
{"LivraisonPays":"France" , "year":2020 , "Prix":7 },
{"LivraisonPays":"France" , "year":2013 , "Prix":7 },
{"LivraisonPays":"France" , "year":2012 , "Prix":7 },
{"LivraisonPays":"France" , "year":2012 , "Prix":8 },
{"LivraisonPays":"France" , "year":2019 , "Prix":8 },
{"LivraisonPays":"France" , "year":2017 , "Prix":8 },
{"LivraisonPays":"France" , "year":2017 , "Prix":8 },
{"LivraisonPays":"France" , "year":2013 , "Prix":8 },
{"LivraisonPays":"France" , "year":2013 , "Prix":8 },
{"LivraisonPays":"France" , "year":2014 , "Prix":8 },
{"LivraisonPays":"France" , "year":2015 , "Prix":9 },
{"LivraisonPays":"France" , "year":2021 , "Prix":10 },
{"LivraisonPays":"France" , "year":2022 , "Prix":10 },
{"LivraisonPays":"France" , "year":2012 , "Prix":10 },
{"LivraisonPays":"France" , "year":2012 , "Prix":10 },
{"LivraisonPays":"France" , "year":2015 , "Prix":10 },
{"LivraisonPays":"France" , "year":2020 , "Prix":10 },
{"LivraisonPays":"France" , "year":2022 , "Prix":10 },
{"LivraisonPays":"France" , "year":2023 , "Prix":10 },
{"LivraisonPays":"France" , "year":2014 , "Prix":10 },
{"LivraisonPays":"France" , "year":2015 , "Prix":10 },
{"LivraisonPays":"France" , "year":2019 , "Prix":10 },
{"LivraisonPays":"France" , "year":2017 , "Prix":10 },
{"LivraisonPays":"France" , "year":2021 , "Prix":10 },
{"LivraisonPays":"France" , "year":2022 , "Prix":10 },
{"LivraisonPays":"France" , "year":2018 , "Prix":11 },
{"LivraisonPays":"France" , "year":2020 , "Prix":11 },
{"LivraisonPays":"France" , "year":2020 , "Prix":11 },
{"LivraisonPays":"France" , "year":2016 , "Prix":12 },
{"LivraisonPays":"France" , "year":2023 , "Prix":12 },
{"LivraisonPays":"France" , "year":2016 , "Prix":13 },
{"LivraisonPays":"France" , "year":2020 , "Prix":13 },
{"LivraisonPays":"France" , "year":2022 , "Prix":13 },
{"LivraisonPays":"France" , "year":2022 , "Prix":13 },
{"LivraisonPays":"France" , "year":2022 , "Prix":13 },
{"LivraisonPays":"France" , "year":2019 , "Prix":13 },
{"LivraisonPays":"France" , "year":2013 , "Prix":14 },
{"LivraisonPays":"France" , "year":2012 , "Prix":14 },
{"LivraisonPays":"France" , "year":2015 , "Prix":14 },
{"LivraisonPays":"France" , "year":2018 , "Prix":14 },
{"LivraisonPays":"France" , "year":2022 , "Prix":14 },
{"LivraisonPays":"France" , "year":2023 , "Prix":14 },
{"LivraisonPays":"France" , "year":2023 , "Prix":14 },
{"LivraisonPays":"France" , "year":2013 , "Prix":14 },
{"LivraisonPays":"France" , "year":2017 , "Prix":14 },
{"LivraisonPays":"France" , "year":2021 , "Prix":14 },
{"LivraisonPays":"France" , "year":2022 , "Prix":14 },
{"LivraisonPays":"France" , "year":2023 , "Prix":15 },
{"LivraisonPays":"France" , "year":2023 , "Prix":15 },
{"LivraisonPays":"France" , "year":2020 , "Prix":15 },
{"LivraisonPays":"France" , "year":2020 , "Prix":15 },
{"LivraisonPays":"France" , "year":2013 , "Prix":16 },
{"LivraisonPays":"France" , "year":2015 , "Prix":16 },
{"LivraisonPays":"France" , "year":2020 , "Prix":16 },
{"LivraisonPays":"France" , "year":2015 , "Prix":17 },
{"LivraisonPays":"France" , "year":2015 , "Prix":17 },
{"LivraisonPays":"France" , "year":2013 , "Prix":17 },
{"LivraisonPays":"France" , "year":2016 , "Prix":17 },
{"LivraisonPays":"France" , "year":2018 , "Prix":17 },
{"LivraisonPays":"France" , "year":2020 , "Prix":17 },
{"LivraisonPays":"France" , "year":2020 , "Prix":17 },
{"LivraisonPays":"France" , "year":2023 , "Prix":17 },
{"LivraisonPays":"France" , "year":2013 , "Prix":17 },
{"LivraisonPays":"France" , "year":2015 , "Prix":18 },
{"LivraisonPays":"France" , "year":2015 , "Prix":18 },
{"LivraisonPays":"France" , "year":2017 , "Prix":18 },
{"LivraisonPays":"France" , "year":2017 , "Prix":18 },
{"LivraisonPays":"France" , "year":2020 , "Prix":18 },
{"LivraisonPays":"France" , "year":2022 , "Prix":18 },
{"LivraisonPays":"France" , "year":2022 , "Prix":18 },
{"LivraisonPays":"France" , "year":2023 , "Prix":18 },
{"LivraisonPays":"France" , "year":2013 , "Prix":18 },
{"LivraisonPays":"France" , "year":2014 , "Prix":18 },
{"LivraisonPays":"France" , "year":2018 , "Prix":18 },
{"LivraisonPays":"France" , "year":2014 , "Prix":19 },
{"LivraisonPays":"France" , "year":2017 , "Prix":19 },
{"LivraisonPays":"France" , "year":2020 , "Prix":19 },
{"LivraisonPays":"France" , "year":2021 , "Prix":19 },
{"LivraisonPays":"France" , "year":2022 , "Prix":19 },
{"LivraisonPays":"France" , "year":2022 , "Prix":19 },
{"LivraisonPays":"France" , "year":2022 , "Prix":19 },
{"LivraisonPays":"France" , "year":2021 , "Prix":20 },
{"LivraisonPays":"France" , "year":2022 , "Prix":20 },
{"LivraisonPays":"France" , "year":2021 , "Prix":21 },
{"LivraisonPays":"France" , "year":2015 , "Prix":21 },
{"LivraisonPays":"France" , "year":2021 , "Prix":21 },
{"LivraisonPays":"France" , "year":2015 , "Prix":21 },
{"LivraisonPays":"France" , "year":2018 , "Prix":21 },
{"LivraisonPays":"France" , "year":2020 , "Prix":21 },
{"LivraisonPays":"France" , "year":2022 , "Prix":21 },
{"LivraisonPays":"France" , "year":2020 , "Prix":22 },
{"LivraisonPays":"France" , "year":2013 , "Prix":22 },
{"LivraisonPays":"France" , "year":2015 , "Prix":23 },
{"LivraisonPays":"France" , "year":2012 , "Prix":24 },
{"LivraisonPays":"France" , "year":2015 , "Prix":24 },
{"LivraisonPays":"France" , "year":2012 , "Prix":25 },
{"LivraisonPays":"France" , "year":2012 , "Prix":25 },
{"LivraisonPays":"France" , "year":2012 , "Prix":25 },
{"LivraisonPays":"France" , "year":2023 , "Prix":25 },
{"LivraisonPays":"France" , "year":2015 , "Prix":25 },
{"LivraisonPays":"France" , "year":2022 , "Prix":27 },
{"LivraisonPays":"France" , "year":2012 , "Prix":27 },
{"LivraisonPays":"France" , "year":2016 , "Prix":28 },
{"LivraisonPays":"France" , "year":2017 , "Prix":28 },
{"LivraisonPays":"France" , "year":2012 , "Prix":28 },

{"LivraisonPays":"Germany" , "year":2021 , "Prix":8 },
{"LivraisonPays":"Germany" , "year":2012 , "Prix":8 },
{"LivraisonPays":"Germany" , "year":2015 , "Prix":9 },
{"LivraisonPays":"Germany" , "year":2018 , "Prix":9 },
{"LivraisonPays":"Germany" , "year":2023 , "Prix":9 },
{"LivraisonPays":"Germany" , "year":2017 , "Prix":9 },
{"LivraisonPays":"Germany" , "year":2018 , "Prix":9 },
{"LivraisonPays":"Germany" , "year":2022 , "Prix":9 },
{"LivraisonPays":"Germany" , "year":2014 , "Prix":9 },
{"LivraisonPays":"Germany" , "year":2015 , "Prix":10 },
{"LivraisonPays":"Germany" , "year":2019 , "Prix":10 },
{"LivraisonPays":"Germany" , "year":2019 , "Prix":10 },
{"LivraisonPays":"Germany" , "year":2013 , "Prix":10 },
{"LivraisonPays":"Germany" , "year":2015 , "Prix":10 },
{"LivraisonPays":"Germany" , "year":2016 , "Prix":10 },
{"LivraisonPays":"Germany" , "year":2022 , "Prix":10 },
{"LivraisonPays":"Germany" , "year":2014 , "Prix":10 },
{"LivraisonPays":"Germany" , "year":2015 , "Prix":10 },
{"LivraisonPays":"Germany" , "year":2016 , "Prix":10 },
{"LivraisonPays":"Germany" , "year":2018 , "Prix":10 },
{"LivraisonPays":"Germany" , "year":2019 , "Prix":10 },
{"LivraisonPays":"Germany" , "year":2019 , "Prix":10 },
{"LivraisonPays":"Germany" , "year":2020 , "Prix":10 },
{"LivraisonPays":"Germany" , "year":2020 , "Prix":10 },
{"LivraisonPays":"Germany" , "year":2022 , "Prix":10 },
{"LivraisonPays":"Germany" , "year":2014 , "Prix":10 },
{"LivraisonPays":"Germany" , "year":2014 , "Prix":10 },
{"LivraisonPays":"Germany" , "year":2017 , "Prix":10 },
{"LivraisonPays":"Germany" , "year":2017 , "Prix":10 },
{"LivraisonPays":"Germany" , "year":2018 , "Prix":10 },
{"LivraisonPays":"Germany" , "year":2019 , "Prix":10 },
{"LivraisonPays":"Germany" , "year":2020 , "Prix":10 },
{"LivraisonPays":"Germany" , "year":2023 , "Prix":10 },
{"LivraisonPays":"Germany" , "year":2013 , "Prix":10 },
{"LivraisonPays":"Germany" , "year":2013 , "Prix":10 },
{"LivraisonPays":"Germany" , "year":2015 , "Prix":10 },
{"LivraisonPays":"Germany" , "year":2012 , "Prix":10 },
{"LivraisonPays":"Germany" , "year":2013 , "Prix":10 },
{"LivraisonPays":"Germany" , "year":2017 , "Prix":11 },
{"LivraisonPays":"Germany" , "year":2018 , "Prix":11 },
{"LivraisonPays":"Germany" , "year":2019 , "Prix":11 },
{"LivraisonPays":"Germany" , "year":2022 , "Prix":11 },
{"LivraisonPays":"Germany" , "year":2016 , "Prix":12 },
{"LivraisonPays":"Germany" , "year":2013 , "Prix":12 },
{"LivraisonPays":"Germany" , "year":2018 , "Prix":12 },
{"LivraisonPays":"Germany" , "year":2018 , "Prix":12 },
{"LivraisonPays":"Germany" , "year":2018 , "Prix":12 },
{"LivraisonPays":"Germany" , "year":2014 , "Prix":13 },
{"LivraisonPays":"Germany" , "year":2014 , "Prix":13 },
{"LivraisonPays":"Germany" , "year":2015 , "Prix":13 },
{"LivraisonPays":"Germany" , "year":2018 , "Prix":13 },
{"LivraisonPays":"Germany" , "year":2021 , "Prix":13 },
{"LivraisonPays":"Germany" , "year":2022 , "Prix":13 },
{"LivraisonPays":"Germany" , "year":2013 , "Prix":13 },
{"LivraisonPays":"Germany" , "year":2015 , "Prix":13 },
{"LivraisonPays":"Germany" , "year":2015 , "Prix":13 },
{"LivraisonPays":"Germany" , "year":2018 , "Prix":13 },
{"LivraisonPays":"Germany" , "year":2022 , "Prix":13 },
{"LivraisonPays":"Germany" , "year":2013 , "Prix":13 },
{"LivraisonPays":"Germany" , "year":2014 , "Prix":13 },
{"LivraisonPays":"Germany" , "year":2019 , "Prix":13 },
{"LivraisonPays":"Germany" , "year":2023 , "Prix":13 },
{"LivraisonPays":"Germany" , "year":2013 , "Prix":14 },
{"LivraisonPays":"Germany" , "year":2015 , "Prix":14 },
{"LivraisonPays":"Germany" , "year":2016 , "Prix":14 },
{"LivraisonPays":"Germany" , "year":2018 , "Prix":14 },
{"LivraisonPays":"Germany" , "year":2023 , "Prix":14 },
{"LivraisonPays":"Germany" , "year":2016 , "Prix":14 },
{"LivraisonPays":"Germany" , "year":2016 , "Prix":14 },
{"LivraisonPays":"Germany" , "year":2017 , "Prix":14 },
{"LivraisonPays":"Germany" , "year":2017 , "Prix":14 },
{"LivraisonPays":"Germany" , "year":2018 , "Prix":14 },
{"LivraisonPays":"Germany" , "year":2019 , "Prix":14 },
{"LivraisonPays":"Germany" , "year":2019 , "Prix":14 },
{"LivraisonPays":"Germany" , "year":2020 , "Prix":14 },
{"LivraisonPays":"Germany" , "year":2020 , "Prix":14 },
{"LivraisonPays":"Germany" , "year":2016 , "Prix":15 },
{"LivraisonPays":"Germany" , "year":2016 , "Prix":15 },
{"LivraisonPays":"Germany" , "year":2017 , "Prix":15 },
{"LivraisonPays":"Germany" , "year":2017 , "Prix":15 },
{"LivraisonPays":"Germany" , "year":2013 , "Prix":15 },
{"LivraisonPays":"Germany" , "year":2018 , "Prix":15 },
{"LivraisonPays":"Germany" , "year":2018 , "Prix":15 },
{"LivraisonPays":"Germany" , "year":2019 , "Prix":15 },
{"LivraisonPays":"Germany" , "year":2014 , "Prix":15 },
{"LivraisonPays":"Germany" , "year":2018 , "Prix":15 },
{"LivraisonPays":"Germany" , "year":2019 , "Prix":15 },
{"LivraisonPays":"Germany" , "year":2019 , "Prix":15 },
{"LivraisonPays":"Germany" , "year":2021 , "Prix":15 },
{"LivraisonPays":"Germany" , "year":2017 , "Prix":16 },
{"LivraisonPays":"Germany" , "year":2016 , "Prix":16 },
{"LivraisonPays":"Germany" , "year":2016 , "Prix":16 },
{"LivraisonPays":"Germany" , "year":2022 , "Prix":16 },
{"LivraisonPays":"Germany" , "year":2012 , "Prix":16 },
{"LivraisonPays":"Germany" , "year":2021 , "Prix":17 },
{"LivraisonPays":"Germany" , "year":2012 , "Prix":17 },
{"LivraisonPays":"Germany" , "year":2021 , "Prix":17 },
{"LivraisonPays":"Germany" , "year":2021 , "Prix":17 },
{"LivraisonPays":"Germany" , "year":2014 , "Prix":17 },
{"LivraisonPays":"Germany" , "year":2015 , "Prix":17 },
{"LivraisonPays":"Germany" , "year":2018 , "Prix":17 },
{"LivraisonPays":"Germany" , "year":2020 , "Prix":17 },
{"LivraisonPays":"Germany" , "year":2021 , "Prix":17 },
{"LivraisonPays":"Germany" , "year":2015 , "Prix":17 },
{"LivraisonPays":"Germany" , "year":2013 , "Prix":18 },
{"LivraisonPays":"Germany" , "year":2014 , "Prix":18 },
{"LivraisonPays":"Germany" , "year":2016 , "Prix":18 },
{"LivraisonPays":"Germany" , "year":2016 , "Prix":18 },
{"LivraisonPays":"Germany" , "year":2016 , "Prix":18 },
{"LivraisonPays":"Germany" , "year":2017 , "Prix":18 },
{"LivraisonPays":"Germany" , "year":2017 , "Prix":18 },
{"LivraisonPays":"Germany" , "year":2017 , "Prix":18 },
{"LivraisonPays":"Germany" , "year":2018 , "Prix":18 },
{"LivraisonPays":"Germany" , "year":2019 , "Prix":18 },
{"LivraisonPays":"Germany" , "year":2019 , "Prix":18 },
{"LivraisonPays":"Austria" , "year":2015 , "Prix":3 },
{"LivraisonPays":"Austria" , "year":2016 , "Prix":4 },
{"LivraisonPays":"Austria" , "year":2012 , "Prix":4 },
{"LivraisonPays":"Austria" , "year":2014 , "Prix":5 },
{"LivraisonPays":"Austria" , "year":2017 , "Prix":6 },
{"LivraisonPays":"Austria" , "year":2016 , "Prix":7 },
{"LivraisonPays":"Austria" , "year":2013 , "Prix":7 },
{"LivraisonPays":"Austria" , "year":2020 , "Prix":9 },
{"LivraisonPays":"Austria" , "year":2020 , "Prix":10 },
{"LivraisonPays":"Austria" , "year":2021 , "Prix":10 },
{"LivraisonPays":"Austria" , "year":2022 , "Prix":10 },
{"LivraisonPays":"Austria" , "year":2018 , "Prix":10 },
{"LivraisonPays":"Austria" , "year":2022 , "Prix":10 },
{"LivraisonPays":"Austria" , "year":2017 , "Prix":10 },
{"LivraisonPays":"Austria" , "year":2017 , "Prix":10 },
{"LivraisonPays":"Austria" , "year":2021 , "Prix":10 },
{"LivraisonPays":"Austria" , "year":2021 , "Prix":11 },
{"LivraisonPays":"Austria" , "year":2012 , "Prix":11 },
{"LivraisonPays":"Austria" , "year":2022 , "Prix":13 },
{"LivraisonPays":"Austria" , "year":2022 , "Prix":13 },
{"LivraisonPays":"Austria" , "year":2015 , "Prix":13 },
{"LivraisonPays":"Austria" , "year":2017 , "Prix":14 },
{"LivraisonPays":"Austria" , "year":2013 , "Prix":14 },
{"LivraisonPays":"Austria" , "year":2015 , "Prix":15 },
{"LivraisonPays":"Austria" , "year":2021 , "Prix":16 },
{"LivraisonPays":"Austria" , "year":2022 , "Prix":17 },
{"LivraisonPays":"Austria" , "year":2021 , "Prix":18 },
{"LivraisonPays":"Austria" , "year":2021 , "Prix":18 },
{"LivraisonPays":"Austria" , "year":2022 , "Prix":18 },
{"LivraisonPays":"Austria" , "year":2021 , "Prix":19 },
{"LivraisonPays":"Austria" , "year":2013 , "Prix":19 },
{"LivraisonPays":"Austria" , "year":2013 , "Prix":20 },
{"LivraisonPays":"Austria" , "year":2017 , "Prix":21 },
{"LivraisonPays":"Austria" , "year":2017 , "Prix":21 },
{"LivraisonPays":"Austria" , "year":2017 , "Prix":22 },
{"LivraisonPays":"Austria" , "year":2013 , "Prix":22 },
{"LivraisonPays":"Austria" , "year":2021 , "Prix":25 },
{"LivraisonPays":"Austria" , "year":2022 , "Prix":25 },
{"LivraisonPays":"Austria" , "year":2013 , "Prix":30 },
{"LivraisonPays":"Austria" , "year":2014 , "Prix":30 },
{"LivraisonPays":"Austria" , "year":2022 , "Prix":32 },
{"LivraisonPays":"Austria" , "year":2015 , "Prix":33 },
{"LivraisonPays":"Austria" , "year":2015 , "Prix":34 },
{"LivraisonPays":"Austria" , "year":2021 , "Prix":35 },
{"LivraisonPays":"Austria" , "year":2022 , "Prix":36 }
];
var visualization = d3plus.viz() 
.container("#viz1") 
.data(sample_data) 
.type("line")
 .id(["LivraisonPays"])  
.x("year")
.y("Prix")
.draw() 
</script>
 Thank you

**Comment by davelandry** [comment]
Not sure why that example is breaking... but if you move to the newer d3plus 2.0 it works great: https://jsfiddle.net/d1s6ugrh/

We haven't change the main github repo over to 2.0 yet, but all of the current [examples](http://d3plus.org/examples/) and [docs](http://d3plus.org/docs/) are for 2.0 and I've been using it in production for a while now. It's almost at feature parity with 1.0.
